scr/Dev.App/ViewModels/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Dev.App.ViewModels
{
    public class CustomerViewModel
    {
        [Key]
        public Guid Id { get; set; }
        
        [DisplayName("Cliente")]
        [Required(ErrorMessage = "O campo {0} é obrigátorio")]
        public string Name { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigátorio")]
        public string CNPJ { get; set; }
        
        [Required(ErrorMessage = "O campo {0} é obrigátorio")]
        public string Email { get; set; }

        [DisplayName("Segmento")]
        [Required(ErrorMessage = "O campo {0} é obrigátorio")]
        public Guid SegmentId { get; set; }
        public SegmentViewModel Segment { get; set; }
        public IEnumerable<SegmentViewModel> Segments { get; set; }
        public IEnumerable<ProspectViewModel> Prospects { get; set; }
    }
}

scr/Dev.App/Controllers/CustomersController.cs
using AutoMapper;
using Dev.App.Extensions;
using Dev.App.ViewModels;
using Dev.Business.Interfaces;
using Dev.Business.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Dev.App.Controllers
{
    [Route("clientes")]
    public class CustomersController : BaseController
    {
        private readonly IMapper _mapper;
        private readonly ISegmentRepository _segmentRepository;
        private readonly ICustomerRepository _customerRepository;
        private readonly ICustomerService _customerService;
        public CustomersController(
            ISegmentRepository segmentRepository,
            ICustomerRepository customerRepository,
            ICustomerService customerService,
            IMapper mapper,
            INotifier notificador) : base(notificador)
        {
            _segmentRepository = segmentRepository;
            _customerRepository = customerRepository;
            _customerService = customerService;
            _mapper = mapper;
        }

        [AllowAnonymous]
        [HttpGet]
        [Route("buscar-clientes")]
        public IActionResult SearchCustomers(string term)
        {
            try 
            {
                var customers = _mapper.Map<IEnumerable<CustomerViewModel>>(_customerRepository.Buscar(x => x.Name.Contains(term.ToUpper()) || x.CNPJ.Contains(term)).Result);

                return Json(customers);
            }
            catch (Exception e)
            {
                return BadRequest();
            }
        }

        [ClaimsAuthorize("Customer", "Adicionar")]
        [Route("adicionar-atualizar-cliente")]
        public async Task<IActionResult> AddOrEdit()
        {
            var prospectViewModel = new ProspectViewModel();
            prospectViewModel.Customer = new CustomerViewModel();

            prospectViewModel = await PopularListaSegmentos(prospectViewModel);

            return PartialView("_AddOrEdit", prospectViewModel);
        }

        [ClaimsAuthorize("Customer", "Adicionar")]
        [Route("adicionar-atualizar-cliente")]
        [HttpPost]
        public async Task<IActionResult> AddOrEdit(ProspectViewModel prospectViewModel)
        {
            prospectViewModel = await PopularListaSegmentos(prospectViewModel);

            ModelState.Remove("Name");
            ModelState.Remove("ProActive");
            ModelState.Remove("Competition");
            ModelState.Remove("NameCompetitors");
            ModelState.Remove("International");
            ModelState.Remove("Status");
            ModelState.Remove("Opening");
            ModelState.Remove("Type");
            ModelState.Remove("PhaseProspect");
            ModelState.Remove("CategoryId");
            ModelState.Remove("EmployeeId");
            ModelState.Remove("CustomerId");
            ModelState.Remove("CompanyId");

            if (!ModelState.IsValid)
                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "_AddOrEdit", prospectViewModel) });

            var customer = _mapper.Map<Customer>(prospectViewModel.Customer);

            await _customerService.Adicionar(customer);

            if (!OperacaoValida()) 
                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "_AddOrEdit", prospectViewModel) });

            return Json(new { isValid = true, cliente = customer });
        }

        private async Task<ProspectViewModel> PopularListaSegmentos(ProspectViewModel prospect)
        {
            prospect.Customer.Segments = _mapper.Map<IEnumerable<SegmentViewModel>>(await _segmentRepository.ObterTodos());

            return prospect;
        }
    }
}

scr/Dev.App/Extensions/SummaryViewComponent.cs
using Dev.Business.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Dev.App.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly INotifier _notificador;

        public SummaryViewComponent(INotifier notificador)
        {
            _notificador = notificador;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notificador.ObterNotificacoes());

            notificacoes.ForEach(x => ViewData.ModelState.AddModelError(string.Empty, x.Mensagem));

            return View();
        }
    }
}

scr/Dev.App/Views/Customers/_AddOrEdit.cshtml
@model Dev.App.ViewModels.ProspectViewModel

<form asp-action="AddOrEdit" asp-controller="Customers" id="form-customer" onsubmit="return PostCustomer(this);" autocomplete="off">
    <vc:summary></vc:summary>

    <div class="row mb-3">
        <div class="col-lg-12 col-md-12 col-sm-12 col-12">
            <label asp-for="Customer.CNPJ" class="font-weight-bold control-label"></label>
            <input asp-for="Customer.CNPJ" class="form-control" />
            <span asp-validation-for="Customer.CNPJ" class="text-danger"></span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-lg-12 col-md-12 col-sm-12 col-12">
            <label asp-for="Customer.Name" class="font-weight-bold control-label"></label>
            <input asp-for="Customer.Name" class="form-control" />
            <span asp-validation-for="Customer.Name" class="text-danger"></span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-lg-12 col-md-12 col-sm-12 col-12">
            <label asp-for="Customer.Email" class="font-weight-bold control-label"></label>
            <input asp-for="Customer.Email" class="form-control" />
            <span asp-validation-for="Customer.Email" class="text-danger"></span>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-lg-12 col-md-12 col-sm-12 col-12 ">
            <label class="font-weight-bold control-label" asp-for="Customer.SegmentId"></label>
            <div class="ui selection dropdown form-control">
                <input type="hidden" asp-for="Customer.SegmentId" />
                <i class="dropdown icon"></i>
                <div class="default text">Selecione</div>
                <div class="menu">
                    <div class="ui icon search input">
                        <input type="text" placeholder="Search tags...">
                    </div>
                    @foreach (var item in Model.Customer.Segments)
                    {
                        <div class="item" data-value="@item.Id">@item.Name</div>
                    }
                </div>
            </div>
            <span asp-validation-for="Customer.SegmentId" class="text-danger"></span>
        </div>
    </div>
</form>


<script>
    inicializaDropDown();
    BuscaCliente();

</script>